/**
 * Versioned TOTP secret encryption and legacy migration support.
 *
 * Current format: enc:v1:<iv_hex>:<auth_tag_hex>:<ciphertext_hex>
 * Legacy formats:
 * - Base32 plaintext generated by the original TOTP setup flow.
 * - Unversioned AES-GCM ciphertext written by the previous enable route.
 */

import { decrypt, encrypt } from './encryption'
import { prisma } from './prisma'

const ENC_PREFIX = 'enc:v1:'
const LEGACY_PLAINTEXT_PATTERN = /^[A-Z2-7]{32}$/
const LEGACY_CIPHERTEXT_PATTERN = /^[0-9a-f]{32}:[0-9a-f]{32}:[0-9a-f]+$/i

export interface DecryptedTotpSecret {
  secret: string
  needsMigration: boolean
}

export function encryptTotpSecret(secret: string): string {
  if (!LEGACY_PLAINTEXT_PATTERN.test(secret)) {
    throw new Error('Invalid TOTP secret')
  }
  return ENC_PREFIX + encrypt(secret)
}

export function isEncryptedTotpSecret(value: unknown): value is string {
  return typeof value === 'string' && value.startsWith(ENC_PREFIX)
}

export function isLegacyPlaintext(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    LEGACY_PLAINTEXT_PATTERN.test(value)
  )
}

export function isLegacyEncryptedTotpSecret(
  value: unknown
): value is string {
  if (
    typeof value !== 'string' ||
    !LEGACY_CIPHERTEXT_PATTERN.test(value)
  ) {
    return false
  }
  const encryptedData = value.split(':')[2]
  return encryptedData.length % 2 === 0
}

export function decryptTotpSecret(encrypted: string): string {
  if (!isEncryptedTotpSecret(encrypted)) {
    throw new Error('Not a valid encrypted TOTP secret')
  }
  const secret = decrypt(encrypted.slice(ENC_PREFIX.length))
  if (!isLegacyPlaintext(secret)) {
    throw new Error('Decrypted TOTP secret has an invalid format')
  }
  return secret
}

export function decryptTotpSecretWithMigration(
  value: string
): DecryptedTotpSecret {
  if (isEncryptedTotpSecret(value)) {
    return {
      secret: decryptTotpSecret(value),
      needsMigration: false,
    }
  }

  if (isLegacyEncryptedTotpSecret(value)) {
    const secret = decrypt(value)
    if (!isLegacyPlaintext(secret)) {
      throw new Error('Decrypted legacy TOTP secret has an invalid format')
    }
    return { secret, needsMigration: true }
  }

  if (isLegacyPlaintext(value)) {
    return { secret: value, needsMigration: true }
  }

  throw new Error('Invalid TOTP secret format')
}

/**
 * Migrate only when the stored value still matches the value that was
 * successfully verified. A concurrent rotation therefore wins safely.
 */
export async function migrateTotpSecret(
  userId: string,
  originalValue: string,
  plaintextSecret: string
): Promise<boolean> {
  const result = await prisma.user.updateMany({
    where: {
      id: userId,
      twoFactorSecret: originalValue,
    },
    data: {
      twoFactorSecret: encryptTotpSecret(plaintextSecret),
    },
  })
  return result.count === 1
}
